### ISSUE TITLE
Skip non-core Rspack packages

### ISSUE THREAD

**Issue by chenjiahan** [rspack-contrib/install-rspack#1]
- `@rspack/plugin-minify` has been deprecated and should be removed
- `@rspack/plugin-react-refresh` and `@rspack/plugin-preact-refresh` are non-core packages and does not use the same canary version with Rspack core.

![image](https://github.com/user-attachments/assets/6f30f340-c2bc-4987-bd10-3c7764a38980)

**Comment by SoonIter** [comment]
fixed by https://github.com/rspack-contrib/install-rspack/pull/2 and was first released in v0.2.0
